# Generated by Django 4.0.8 on 2022-11-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KOLMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('twitter_url', models.CharField(max_length=255)),
                ('search_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KOL Master',
                'verbose_name_plural': 'KOL Master',
                'db_table': 'kol_master',
            },
        ),
    ]
